"""add baskets to orders

Revision ID: 15dc6b6eb988
Revises: 701c93918945
Create Date: 2025-09-25 23:49:12.910470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "15dc6b6eb988"
down_revision: Union[str, Sequence[str], None] = "701c93918945"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("parent_order_id", sa.String(length=36), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "asset_type",
                sa.Enum("BASKET", "TOKEN", native_enum=False),
                nullable=True,
            )
        )
        batch_op.create_foreign_key(
            "fk_orders_parent_order_id_orders_id", "orders", ["parent_order_id"], ["id"]
        )

    # Set all existing orders to asset_type = 'TOKEN'
    op.execute("UPDATE orders SET asset_type = 'TOKEN' WHERE asset_type IS NULL")

    # Make asset_type non-nullable
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("asset_type", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_orders_parent_order_id_orders_id", type_="foreignkey"
        )
        batch_op.drop_column("asset_type")
        batch_op.drop_column("parent_order_id")

    # ### end Alembic commands ###
