"""empty message

Revision ID: 2ca038a1b4d6
Revises: e2809a156abe
Create Date: 2026-01-02 20:32:48.089987

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2ca038a1b4d6"
down_revision: Union[str, Sequence[str], None] = "e2809a156abe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "confirmed_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("planned_order_id", sa.String(length=36), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column("buy_balance_asset", sa.String(), nullable=False),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column("sell_balance_asset_id", sa.String(), nullable=False),
        sa.Column("sell_balance_asset", sa.String(), nullable=False),
        sa.Column("sell_balance_amount", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["planned_order_id"],
            ["planned_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "signable_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("confirmed_order_id", sa.String(length=36), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column("buy_balance_asset", sa.String(), nullable=False),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("buy_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("sell_balance_asset_id", sa.String(), nullable=False),
        sa.Column("sell_balance_asset", sa.String(), nullable=False),
        sa.Column("sell_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "sell_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("sell_balance_decimals", sa.Integer(), nullable=False),
        sa.Column(
            "signature_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "transaction", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_order_id"],
            ["confirmed_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("signable_orders")
    op.drop_table("confirmed_orders")
    # ### end Alembic commands ###
