"""add asset_type for transactions and postings

Revision ID: 4e66bf9bb094
Revises: c19027354d3c
Create Date: 2025-10-19 19:58:09.345636

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e66bf9bb094"
down_revision: Union[str, Sequence[str], None] = "c19027354d3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "asset_type",
                sa.Enum("BASKET", "TOKEN", native_enum=False),
                nullable=True,
            )
        )

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "asset_type",
                sa.Enum("BASKET", "TOKEN", native_enum=False),
                nullable=True,
            )
        )

    op.execute("UPDATE postings SET asset_type = 'TOKEN'")
    op.execute("UPDATE transactions SET asset_type = 'TOKEN'")

    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.alter_column("asset_type", nullable=False)

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column("asset_type", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("asset_type")

    with op.batch_alter_table("postings", schema=None) as batch_op:
        batch_op.drop_column("asset_type")

    # ### end Alembic commands ###
