"""empty message

Revision ID: 701c93918945
Revises: 494de904dedb
Create Date: 2025-08-16 01:12:29.950506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701c93918945'
down_revision: Union[str, Sequence[str], None] = '494de904dedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('executed_buy_balance_asset_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_buy_balance_asset', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_buy_balance_amount', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_buy_balance_amount_atomic', sa.NUMERIC(precision=78, scale=0), nullable=False))
        batch_op.add_column(sa.Column('executed_buy_balance_decimals', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('executed_sell_balance_asset_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_sell_balance_asset', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_sell_balance_amount', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('executed_sell_balance_amount_atomic', sa.NUMERIC(precision=78, scale=0), nullable=False))
        batch_op.add_column(sa.Column('executed_sell_balance_decimals', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('executed_sell_balance_decimals')
        batch_op.drop_column('executed_sell_balance_amount_atomic')
        batch_op.drop_column('executed_sell_balance_amount')
        batch_op.drop_column('executed_sell_balance_asset')
        batch_op.drop_column('executed_sell_balance_asset_id')
        batch_op.drop_column('executed_buy_balance_decimals')
        batch_op.drop_column('executed_buy_balance_amount_atomic')
        batch_op.drop_column('executed_buy_balance_amount')
        batch_op.drop_column('executed_buy_balance_asset')
        batch_op.drop_column('executed_buy_balance_asset_id')

    # ### end Alembic commands ###
