"""empty message

Revision ID: 952eca8f7916
Revises: 2ca038a1b4d6
Create Date: 2026-01-02 21:29:07.234683

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "952eca8f7916"
down_revision: Union[str, Sequence[str], None] = "2ca038a1b4d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "executed_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("signable_order_id", sa.String(length=36), nullable=False),
        sa.Column("transaction_hash", sa.String(length=66), nullable=False),
        sa.Column("address", sa.String(length=42), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_asset", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("buy_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("sell_balance_asset_id", sa.String(), nullable=False),
        sa.Column(
            "sell_balance_asset",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("sell_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "sell_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("sell_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("rate", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["signable_order_id"],
            ["signable_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("executed_orders")
    # ### end Alembic commands ###
