"""add chain transaction tx fields

Revision ID: 9ce79696689d
Revises: 04b74ce1d17e
Create Date: 2025-10-16 15:16:14.184752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ce79696689d'
down_revision: Union[str, Sequence[str], None] = '04b74ce1d17e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add 'amount' column as nullable
    with op.batch_alter_table('order_try_chain_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=78, scale=0), nullable=True))
        batch_op.add_column(sa.Column('to_address', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # 2. Set all existing 'amount' values to 0
    op.execute("UPDATE order_try_chain_transactions SET amount = 0")

    # 3. Alter 'amount' column to be non-nullable
    with op.batch_alter_table('order_try_chain_transactions', schema=None) as batch_op:
        batch_op.alter_column('amount', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_try_chain_transactions', schema=None) as batch_op:
        batch_op.drop_column('gas')
        batch_op.drop_column('to_address')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
