"""empty message

Revision ID: b49e2559e23b
Revises: 952eca8f7916
Create Date: 2026-01-08 02:08:19.644520

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b49e2559e23b"
down_revision: Union[str, Sequence[str], None] = "952eca8f7916"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intended_orders", schema=None) as batch_op:
        # Add type column as nullable first
        batch_op.add_column(sa.Column("type", sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column("sell_asset", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("buy_asset", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("amount", sa.String(), nullable=True))
        batch_op.drop_column("buy_asset_with_amount_asset_id")
        batch_op.drop_column("sell_asset_with_amount_asset")
        batch_op.drop_column("buy_asset_with_amount_asset")
        batch_op.drop_column("sell_asset_with_amount_amount")
        batch_op.drop_column("buy_asset_with_amount_amount")
        batch_op.drop_column("sell_asset_with_amount_asset_id")

    # Fill type column with "SELL" for existing rows
    op.execute("UPDATE intended_orders SET type = 'SELL' WHERE type IS NULL")

    # Make type column not nullable
    with op.batch_alter_table("intended_orders", schema=None) as batch_op:
        batch_op.alter_column("type", nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("intended_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sell_asset_with_amount_asset_id",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "buy_asset_with_amount_amount",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "sell_asset_with_amount_amount",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "buy_asset_with_amount_asset",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "sell_asset_with_amount_asset",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "buy_asset_with_amount_asset_id",
                sa.VARCHAR(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("amount")
        batch_op.drop_column("buy_asset")
        batch_op.drop_column("sell_asset")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
