"""make hash column nullable

Revision ID: c19027354d3c
Revises: 9ce79696689d
Create Date: 2025-10-17 15:45:48.404317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c19027354d3c'
down_revision: Union[str, Sequence[str], None] = '9ce79696689d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_try_chain_transactions', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_try_chain_transactions', schema=None) as batch_op:
        batch_op.alter_column('hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
