"""empty message

Revision ID: e2809a156abe
Revises: 31149a9bb332
Create Date: 2026-01-02 03:03:18.579138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2809a156abe'
down_revision: Union[str, Sequence[str], None] = '31149a9bb332'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intended_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('buy_asset_with_amount_asset_id', sa.String(), nullable=True),
    sa.Column('buy_asset_with_amount_asset', sa.String(), nullable=True),
    sa.Column('buy_asset_with_amount_amount', sa.String(), nullable=True),
    sa.Column('sell_asset_with_amount_asset_id', sa.String(), nullable=True),
    sa.Column('sell_asset_with_amount_asset', sa.String(), nullable=True),
    sa.Column('sell_asset_with_amount_amount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planned_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('address', sa.String(length=42), nullable=False),
    sa.Column('buy_asset_with_amount_asset_id', sa.String(), nullable=False),
    sa.Column('buy_asset_with_amount_asset', sa.String(), nullable=False),
    sa.Column('buy_asset_with_amount_available_amount', sa.String(), nullable=False),
    sa.Column('buy_asset_with_amount_amount', sa.String(), nullable=True),
    sa.Column('sell_asset_with_amount_asset_id', sa.String(), nullable=False),
    sa.Column('sell_asset_with_amount_asset', sa.String(), nullable=False),
    sa.Column('sell_asset_with_amount_available_amount', sa.String(), nullable=False),
    sa.Column('sell_asset_with_amount_amount', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planned_orders')
    op.drop_table('intended_orders')
    # ### end Alembic commands ###
