name: coinbasket_data_agent_test
services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant_test
    ports:
      - ${QDRANT_PORT}:6333
      - ${QDRANT_GRPC_PORT}:6334
    expose:
      - 6333
      - 6334
    environment:
      QDRANT__SERVICE__API_KEY: ${QDRANT_API_KEY}
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - qdrant:/qdrant/storage

configs:
  qdrant_config:
    content: |
      log_level: INFO
volumes:
  qdrant: