"""remove Orders.parent_order fk

Revision ID: 04c8e4379ab7
Revises: 1b3d6530b218
Create Date: 2025-10-03 23:35:07.277687

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '04c8e4379ab7'
down_revision: Union[str, Sequence[str], None] = '1b3d6530b218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_orders_parent_order_id_orders_id'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_orders_parent_order_id_orders_id'), 'orders', ['parent_order_id'], ['id'])

    # ### end Alembic commands ###
