"""empty message

Revision ID: 0d68bc57a028
Revises:
Create Date: 2025-08-12 14:12:38.127947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0d68bc57a028"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sell_balance_asset_id", sa.String(), nullable=False),
        sa.Column("sell_balance_asset", sa.String(), nullable=False),
        sa.Column("sell_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "sell_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("sell_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column("buy_balance_asset", sa.String(), nullable=False),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("buy_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("basket_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sell_balance_asset_id", sa.String(), nullable=False),
        sa.Column("sell_balance_asset", sa.Text(), nullable=False),
        sa.Column("sell_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "sell_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("sell_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column("buy_balance_asset", sa.Text(), nullable=False),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("buy_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("transaction_hash", sa.String(), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("fees", sa.Text(), nullable=True),
        sa.Column("basket_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_tries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("buy_balance_asset_id", sa.String(), nullable=False),
        sa.Column("buy_balance_asset", sa.String(), nullable=False),
        sa.Column("buy_balance_amount", sa.String(), nullable=False),
        sa.Column(
            "buy_balance_amount_atomic",
            sa.NUMERIC(precision=78, scale=0),
            nullable=False,
        ),
        sa.Column("buy_balance_decimals", sa.Integer(), nullable=False),
        sa.Column("fees", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_try_chain_transactions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("try_id", sa.String(length=36), nullable=False),
        sa.Column("order_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("data", sa.String(), nullable=False),
        sa.Column("hash", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["try_id"],
            ["order_tries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_try_chain_transactions")
    op.drop_table("order_tries")
    op.drop_table("transactions")
    op.drop_table("orders")
    # ### end Alembic commands ###
