"""add posting_parent_id and transaction_parent_id

Revision ID: 1b3d6530b218
Revises: 15dc6b6eb988
Create Date: 2025-10-03 23:21:07.022694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b3d6530b218'
down_revision: Union[str, Sequence[str], None] = '15dc6b6eb988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_posting_id', sa.String(length=40), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=40),
               existing_nullable=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_transaction_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('parent_transaction_id')

    with op.batch_alter_table('postings', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
        batch_op.drop_column('parent_posting_id')

    # ### end Alembic commands ###
