"""create buy and sell basket id

Revision ID: 31149a9bb332
Revises: 4e66bf9bb094
Create Date: 2025-11-05 03:32:57.558452

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31149a9bb332"
down_revision: Union[str, Sequence[str], None] = "4e66bf9bb094"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.alter_column("basket_id", new_column_name="buy_basket_id")
        batch_op.add_column(sa.Column("sell_basket_id", sa.String(), nullable=True))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.alter_column("basket_id", new_column_name="buy_basket_id")
        batch_op.add_column(sa.Column("sell_basket_id", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("sell_basket_id")
        batch_op.alter_column("buy_basket_id", new_column_name="basket_id")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("sell_basket_id")
        batch_op.alter_column("buy_basket_id", new_column_name="basket_id")

    # ### end Alembic commands ###
