"""empty message

Revision ID: 494de904dedb
Revises: b62411ec8deb
Create Date: 2025-08-15 03:16:34.613426

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "494de904dedb"
down_revision: Union[str, Sequence[str], None] = "b62411ec8deb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_transactions_orders", "orders", ["order_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_transactions_orders", type_="foreignkey")

    # ### end Alembic commands ###
