"""empty message

Revision ID: b62411ec8deb
Revises: 0d68bc57a028
Create Date: 2025-08-13 03:49:52.761346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b62411ec8deb'
down_revision: Union[str, Sequence[str], None] = '0d68bc57a028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('asset', sa.String(), nullable=False),
    sa.Column('amount', sa.String(), nullable=False),
    sa.Column('amount_atomic', sa.NUMERIC(precision=78, scale=0), nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SELL', 'BUY', 'SWAP', native_enum=False), nullable=False),
    sa.Column('basket_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postings')
    # ### end Alembic commands ###
