services:
  ganache:
    image: node:20
    container_name: ganache
    ports:
      - "8545:8545"
    working_dir: /app
    entrypoint: >
      sh -c '
      npm install -g ganache &&
      ganache --fork.url=${GANACHE_FORK_URL} --logging.verbose=true --mnemonic "${GANACHE_MNEMONIC}" --server.host=0.0.0.0'