name: coinbasket_invest_agent
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8545:8545"
    entrypoint: ["anvil"]
    command: [ "--balance", "10", "--chain-id", "${ANVIL_CHAIN_ID}", "--fork-url", "${ANVIL_FORK_URL}", "--mnemonic", "${ANVIL_MNEMONIC}" ]
    volumes:
      - anvil-data:/anvil/state
  postgres:
    image: postgres:17.5
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${AGENT_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redoc:
    container_name: redoc
    image: redocly/redoc
    ports:
      - "${REDOC_PORT}:80"
    environment:
      SPEC_URL: "http://127.0.0.1:${AGENT_PORT}/openapi"
  temporal:
    container_name: temporal
    image: temporalio/temporal:1.5.0
    command: ["server", "start-dev", "--ip", "0.0.0.0"]
    ports:
      - "${TEMPORAL_PORT}:7233"
      - "${TEMPORAL_WEB_PORT}:8233"
    volumes:
      - temporal-data:/tmp/temporal
volumes:
  postgres-data:
  anvil-data:
  temporal-data: