name: coinbasket_invest_agent
services:
  anvil:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    container_name: anvil
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8545:8545"
    entrypoint: ["anvil"]
    command: [ "--balance", "10", "--chain-id", "${ANVIL_CHAIN_ID}", "--fork-url", "${ANVIL_FORK_URL}", "--mnemonic", "${ANVIL_MNEMONIC}" ]
  redoc:
    container_name: redoc
    image: redocly/redoc
    ports:
      - "${REDOC_PORT}:80"
    environment:
      SPEC_URL: "http://127.0.0.1:${AGENT_PORT}/openapi"