name: coinbasket_invest_agent_test
services:
  anvil_test:
    image: ghcr.io/foundry-rs/foundry:v1.2.3
    container_name: anvil_test
    environment:
      ANVIL_IP_ADDR: "0.0.0.0"
    working_dir: /anvil
    ports:
      - "8546:8545"
    entrypoint: ["anvil"]
    command: [ "--balance", "10000", "--chain-id", "${ANVIL_CHAIN_ID}", "--fork-url", "${ANVIL_FORK_URL}", "--mnemonic", "${ANVIL_MNEMONIC}" ]
  postgres_test:
    image: postgres:17.5
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${AGENT_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - /var/lib/postgresql/data