[tool.coverage.run]
branch = true
source = [ "protocol" ]

[tool.coverage.report]
exclude_lines = ['if TYPE_CHECKING:']
show_missing = true

[tool.pytest.ini_options]
addopts = """
 --cov
 --cov-report html:'../coverage/protocol/html'
 --cov-report xml:'../coverage/protocol/coverage.xml'
 --html='../reports/protocol/unittests/html/index.html'
 --junitxml='../reports/protocol/unittests/junit.xml'
"""

[tool.poetry]
name = "protocol"
version = "0.0.1"
description = "🧺 invest agent &lt;-&gt; data agent protocol"
authors = [
  "mehdidotcafe"
]
license = 'Proprietary'
readme = 'README.md'

  [[tool.poetry.packages]]
  include = "protocol"

  [tool.poetry.dependencies]
  python = ">=3.10,<4.0"
  uagents = ">=0.22.3,<0.23.0"

  [tool.poetry.group.dev.dependencies]
  autopep8 = "2.3.1"
  ruff = ">=0.11.4,<0.12.0"
  pytest = "8.3.5"
  pytest-sugar = "1.0.0"
  pytest-cov = "6.0.0"
  pytest-html = "4.1.1"
  pytest-watch = "4.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
