from typing import Literal


AssetCategory = Literal[
    # Coinbasket custom categories
    "Basket",
    "Coinbasket Selection",
    "DTF",
    "Native Token",
    # Coingecko categories
    "0g Ecosystem",
    "4chan-Themed",
    "8Bit Chain Ecosystem",
    "aarna Vault Tokens",
    "Aave Tokens",
    "Abstract Ecosystem",
    "Account Abstraction",
    "Action Games",
    "Adidas Ecosystem",
    "Adventure Games",
    "Aelf Ecosystem",
    "AI Agent Launchpad",
    "AI Agents",
    "AI Applications",
    "AI Framework",
    "AI Meme",
    "AirDAO Ecosystem",
    "Airdropped Tokens by NFT Projects",
    "Alameda Research Portfolio",
    "Alephium Ecosystem",
    "Algorand Ecosystem",
    "Algorithmic Stablecoin",
    "AlienX Ecosystem",
    "Alleged SEC Securities",
    "Alveychain Ecosystem",
    "Analytics",
    "Ancient8 Ecosystem",
    "Andreessen Horowitz (a16z) Portfolio",
    "Animal Racing",
    "Anime-Themed",
    "Animoca Brands Portfolio",
    "ApeChain Ecosystem",
    "Apex Chain Ecosystem",
    "Appchains",
    "Aptos Ecosystem",
    "Arbitrum Ecosystem",
    "Arbitrum Nova Ecosystem",
    "Arcade Games",
    "Archway Ecosystem",
    "Areum Network Ecosystem",
    "Art",
    "Art Blocks Ecosystem",
    "Artela Ecosystem",
    "Artificial Intelligence (AI)",
    "ASC-20",
    "Asset Manager",
    "Astar Ecosystem",
    "Astar zkEVM Ecosystem",
    "Atomicals (ARC-20)",
    "Augmented Reality",
    "Aurora Ecosystem",
    "Automated Market Maker (AMM)",
    "Avalanche Ecosystem",
    "Avalanche L1",
    "Axie Infinity Ecosystem",
    "Azuki Ecosystem",
    "BackedFi xStocks Ecosystem",
    "BagsApp Ecosystem",
    "Bahamut Ecosystem",
    "Base Ecosystem",
    "Base Meme",
    "Bayblon Genesis Ecosystem",
    "Beam Ecosystem",
    "BeamPrivacy Ecosystem",
    "Believe.app Ecosystem",
    "Berachain Ecosystem",
    "BESC HyperChain Ecosystem",
    "BEVM Ecosystem",
    "Big Data",
    "Binance Alpha Spotlight",
    "Binance Buildkey TGE",
    "Binance HODLer Airdrops",
    "Binance Launchpad",
    "Binance Launchpool",
    "Binance Megadrop",
    "Binance-Peg Tokens",
    "Binance Wallet IDO",
    "Bitcichain Ecosystem",
    "Bitcoin Ecosystem",
    "Bitcoin Fork",
    "Bitcoin Meme",
    "Bitcoin Sidechains",
    "Bitgert Ecosystem",
    "Bitlayer Ecosystem",
    "Bitrock Ecosystem",
    "BitStarters Launchpad",
    "Bittensor Ecosystem",
    "Bittensor EVM Ecosystem",
    "Bittensor Subnets",
    "BitTorrent Ecosystem",
    "Blast Ecosystem",
    "Blockchain Capital Portfolio",
    "BNB Chain Ecosystem",
    "Boba BNB Ecosystem",
    "Boba Network Ecosystem",
    "BOB Network Ecosystem",
    "BONK.fun Ecosystem",
    "Bored Ape Ecosystem",
    "Botanix Ecosystem",
    "BounceBit Ecosystem",
    "BRC-20",
    "Breeding",
    "Bridged DAI",
    "Bridged FRAX",
    "Bridged Stablecoin",
    "Bridged-Tokens",
    "Bridged USDC",
    "Bridged USDT",
    "Bridged WAVAX",
    "Bridged WBNB",
    "Bridged WBTC",
    "Bridged WETH",
    "Bridged wstETH",
    "Bridge Governance Tokens",
    "BSquared Network Ecosystem",
    "BTCfi Protocol",
    "Buidlpad Launchpad",
    "Business Services",
    "Camelot Launchpad",
    "Canto Ecosystem",
    "Capital Launchpad",
    "Cardano Ecosystem",
    "Card Games",
    "CarrChain Ecosystem",
    "Cat-Themed",
    "CeFi",
    "Celebrity-Themed",
    "Celer Network",
    "Celo Ecosystem",
    "Centralized Exchange (CEX) Product",
    "Centralized Exchange (CEX) Token",
    "Chain Abstraction",
    "ChainGPT Launchpad",
    "Charity",
    "Chiliz Ecosystem",
    "Chinese Meme",
    "Christmas Themed",
    "Chromia Ecosystem",
    "Circle Ventures Portfolio",
    "Clanker Ecosystem",
    "CNY Stablecoin",
    "Codex Ecosystem",
    "Coinbase 50 Index",
    "Coinbase Ventures Portfolio",
    "CoinList Launchpad",
    "Collectibles",
    "Combo Ecosystem",
    "Commodity-backed Stablecoin",
    "Communication",
    "Compound Tokens",
    "Conflux Ecosystem",
    "Consensys Portfolio",
    "Cookie Launchpad",
    "Core Ecosystem",
    "Corn Ecosystem",
    "Cosmos Ecosystem",
    "COTI Ecosystem",
    "Country-Themed Meme",
    "CreatorBid Ecosystem",
    "Cronos Ecosystem",
    "Cronos zkEVM Ecosystem",
    "Cross-chain Communication",
    "CrossFi Ecosystem",
    "Crypto-backed Stablecoin",
    "Crypto-Backed Tokens",
    "cToken",
    "Curve Ecosystem",
    "Cyber Ecosystem",
    "CyberKongz Ecosystem",
    "Cybersecurity",
    "DaoMaker Launchpad",
    "daos.fun Ecosystem",
    "Data Availability",
    "Decentralized Exchange (DEX)",
    "Decentralized Finance (DeFi)",
    "Decentralized Identifier (DID)",
    "Decentralized Lottery",
    "Decentralized Science (DeSci)",
    "Decentralized Social Media (DeSOC)",
    "DeepBrain Chain Ecosystem",
    "DeFAI",
    "DeFiance Capital Portfolio",
    "DeFi Index",
    "DefiMetaChain Ecosystem",
    "Defiverse Ecosystem",
    "Degen Ecosystem",
    "DeLabs",
    "Delphi Ventures Portfolio",
    "DePIN",
    "Derivatives",
    "Desci Meme",
    "Dex Aggregator",
    "DFK Chain Ecosystem",
    "Dinari Ecosystem",
    "Directed Acyclic Graph (DAG)",
    "Discord Bots",
    "DMEX Ecosystem",
    " DN-404",
    "Dogechain Ecosystem",
    "Dog-Themed",
    "Doodles LLC",
    "DragonFly Capital Portfolio",
    "DRC-20",
    "DuckChain Ecosystem",
    "Duck-Themed",
    "DWF Labs Portfolio",
    "Echo Launchpad",
    "Eclipse Ecosystem",
    "E-commerce",
    "Edgeware Ecosystem",
    "Education",
    "EDU Chain Ecosystem",
    "eGirl Capital Portfolio",
    "Elastos Smart Contract Chain Ecosystem",
    "Electroneum Ecosystem",
    "Elon Musk-Inspired",
    "Elysium Ecosystem",
    "Emoji-Themed",
    "Endurance Ecosystem",
    "Energi Ecosystem",
    "Energy",
    "Entertainment",
    "ENULS Ecosystem",
    "EOS Ecosystem",
    "ERC20i",
    "ERC 404",
    "Ergo Ecosystem",
    "ETF",
    "Ethereum Classic Ecosystem",
    "Ethereum Ecosystem",
    "Ethereum PoS IOU",
    "EthereumPoW Ecosystem",
    "Ether.fi Ecosystem",
    "Etherlink Ecosystem",
    "EUR Stablecoin",
    "Eventum Ecosystem",
    "Evmos Ecosystem",
    "Exchange-based Tokens",
    "F1 Partnership",
    "Fan Token",
    "Fantom Ecosystem",
    "Farcaster Ecosystem",
    "Farming-as-a-Service (FaaS)",
    "Farming Games",
    "Fiat-backed Stablecoin",
    "Fighting Games",
    "Fixed Interest",
    "Flare Network Ecosystem",
    "Flaunch Ecosystem",
    "Floor Protocol Tokens",
    "Flow Ecosystem",
    "Flow EVM Ecosystem",
    "Four.meme Ecosystem (BNB Memes)",
    "Fractionalized NFT",
    "Fraxtal Ecosystem",
    "Friend.tech Ecosystem",
    "Frog-Themed",
    "FTX Holdings",
    "Fuse Ecosystem",
    "GalaChain Ecosystem",
    "Galaxy Digital Portfolio",
    "Gambling (GambleFi)",
    "Game Studio",
    "Gaming Blockchains",
    "Gaming (GameFi)",
    "Gaming Governance Token",
    "Gaming Marketplace",
    "Gaming Platform",
    "Gaming Utility Token",
    "Gate Fun Ecosystem",
    "GateLayer Ecosystem",
    "GBP Stablecoin",
    "Genesys Network Ecosystem",
    "Gig Economy",
    "Glue Ecosystem",
    "GMCI 30 Index",
    "GMCI DeFi Index",
    "GMCI DePIN Index",
    "GMCI Index",
    "GMCI Layer 1 Index",
    "GMCI Layer 2 Index",
    "GMCI Meme Index",
    "Gnosis Chain Ecosystem",
    "Goat Ecosystem",
    "Gotchiverse",
    "Governance",
    "Graphite Network Ecosystem",
    "GraphLinq Ecosystem",
    "Gravity Alpha Ecosystem",
    "GRX Chain Ecosystem",
    "Guild and Scholarship",
    "GUNZ Ecosystem",
    "Ham Ecosystem",
    "Haqq Network Ecosystem",
    "Harmony Ecosystem",
    "HashKey Chain Ecosystem",
    "Haven1 Ecosystem",
    "Healthcare",
    "HECO Chain Ecosystem",
    "Hedera Ecosystem",
    "HeLa Ecosystem",
    "Hemi Ecosystem",
    "Henesys Ecosystem",
    "Humanode Ecosystem",
    "Huobi ECO Chain Ecosystem",
    "Hybrid Token Standards",
    "Hydra Ecosystem",
    "Hydration Ecosystem",
    "HyperEVM Ecosystem",
    "Hyperliquid Ecosystem",
    "Hyperunit Ecosystem",
    "HyperXpad Launchpad",
    "ICB Network Ecosystem",
    "IDR Stablecoin",
    "Immutable zkEVM Ecosystem",
    "Impossible Finance Launchpad",
    "Index",
    "Index Coop Defi Index",
    "Index Coop Index",
    "Index Coop Metaverse Index",
    "inEVM Ecosystem",
    "InfoFi",
    "Infrastructure",
    "Initia Ecosystem",
    "Injective Ecosystem",
    "Ink Ecosystem",
    "Inscriptions",
    "Insurance",
    "Intent",
    "Internet Computer Ecosystem",
    "Internet of Things (IOT)",
    "Interoperability",
    "IOTA Ecosystem",
    "IOTA EVM Ecosystem",
    "IoTeX Ecosystem",
    "IOU tokens",
    "IP",
    "IP Meme",
    "Jack Butcher Ecosystem",
    "Jibchain Ecosystem",
    "JPY Stablecoin",
    "Juno Ecosystem",
    "Jupiter DTF Launchpad",
    "Kadena Ecosystem",
    "Kaia Ecosystem",
    "KardiaChain Ecosystem",
    "Kaspa Ecosystem",
    "Katana Ecosystem",
    "Kava Ecosystem",
    "Kinto Ecosystem",
    "Kommunitas Launchpad",
    "Kroma Ecosystem",
    "KRW Stablecoin",
    "Kucoin Community Chain Ecosystem",
    "Kujira Ecosystem",
    "Laika Ecosystem",
    "Lamina1 Ecosystem",
    "Large-Cap PFP",
    "Larissa Ecosystem",
    "Launchpad",
    "Layer 0 (L0)",
    "Layer 1 (L1)",
    "Layer 2 (L2)",
    "Layer 3 (L3)",
    "Learn to Earn",
    "Legal",
    "Lending/Borrowing Protocols",
    "Lens Ecosystem",
    "Leveraged Token",
    "LightLink Ecosystem",
    "Linea Ecosystem",
    "Liquid Restaked ETH",
    "Liquid Restaked SOL",
    "Liquid Restaking Governance Tokens",
    "Liquid Restaking Tokens",
    "Liquid Staked APT\t",
    "Liquid Staked BTC",
    "Liquid Staked ETH",
    "Liquid Staked HYPE\t",
    "Liquid Staked SOL",
    "Liquid Staked SUI",
    "Liquid Staking",
    "Liquid Staking Governance Tokens",
    "Liquid Staking Tokens",
    "Lisk Ecosystem",
    "Loopring Ecosystem",
    "LP Tokens",
    "LRTfi",
    "LSDFi",
    "Lukso Ecosystem",
    "Lung Ecosystem",
    "Made in China",
    "Made in USA",
    "Mainnetz Ecosystem",
    "Manta Network Ecosystem",
    "Mantle Ecosystem",
    "Mantra Ecosystem",
    "Mantra EVM Ecosystem",
    "Manufacturing",
    "Marketing",
    "Market-Making Solution",
    "Mascot-Themed",
    "Massa Ecosystem",
    "Masternodes",
    "MaxxChain Ecosystem",
    "Media",
    "MegaETH Ecosystem",
    "Meme",
    "Memecoin NFTs",
    "MemeCore Ecosystem",
    "Memeland Ecosystem",
    "Memorial Themed",
    "Merlin Chain Ecosystem",
    "MetaDAO Launchpad",
    "Metagovernance",
    "Metaverse",
    "Meter Ecosystem",
    "Metis Ecosystem",
    "MEV Protection",
    "Mezo Ecosystem",
    "Midas Liquid Yield Tokens",
    "Mid-Cap PFP",
    "Migaloo Ecosystem",
    "Milady And Derivatives",
    "Milkomeda (Cardano) Ecosystem",
    "Mint Ecosystem",
    "MMO",
    "Mobile Mining",
    "Mode Ecosystem",
    "Modular Blockchain",
    "Monad Ecosystem",
    "Moonbeam Ecosystem",
    "Moonchain Ecosystem",
    "Moonriver Ecosystem",
    "Moonshot Ecosystem",
    "Morph L2 Ecosystem",
    "Morpho Ecosystem",
    "Movement Ecosystem",
    "Move To Earn",
    "Multicoin Capital Portfolio",
    "MultiVAC Ecosystem",
    "MultiversX Ecosystem",
    "Murad Picks",
    "Music",
    "Nahmii Ecosystem",
    "Name Service",
    "Near Protocol Ecosystem",
    "Neobank",
    "NEO Ecosystem",
    "Neon Ecosystem",
    "NFT",
    "NFT Aggregator",
    "NFT AMM",
    "NFT Collections That Received Airdrops",
    "NFTFi",
    "NFT Index",
    "NFT Launchpad",
    "NFT Lending/Borrowing",
    "NFT Marketplace",
    "NFTStrategy Ecosystem",
    "NFT Strategy Flywheel",
    "Nibiru Ecosystem",
    "Nike Ecosystem",
    "NounsDAO",
    "Oasis Emerald Ecosystem",
    "Oasis Sapphire Ecosystem",
    "Oasys Ecosystem",
    "OCM Ecosystem",
    "Odyssey Ecosystem",
    "OEC Ecosystem",
    "Ohm Fork",
    "OKT Chain Ecosystem",
    "OKX Ventures Portfolio",
    "Olympus Pro Ecosystem",
    "Omnia Ecosystem",
    "Onchain Ecosystem",
    "On-chain Gaming",
    "Ondo Tokenized Assets",
    "opBNB Ecosystem",
    "Opinions.fun Ecosystem",
    "Optimism Ecosystem",
    "Optimism Superchain Ecosystem",
    "Options",
    "Oracle",
    "Oraichain Ecosystem",
    "Orange Cap Games",
    "Osmosis Ecosystem",
    "Outlier Ventures Portfolio",
    "PAAL AI Launchpad",
    "Pantera Capital Portfolio",
    "Paradigm Portfolio",
    "Parallel Ecosystem",
    "Parallelized EVM",
    "Parex Network Ecosystem",
    "Parody Meme",
    "Payment Solutions",
    "Peaq Ecosystem",
    "Perpetuals",
    "PFP / Avatar",
    "Plasma Ecosystem",
    "PlatON Network Ecosystem",
    "PLAYA3ULL Games Ecosystem",
    "Play To Earn",
    "Plume Network Ecosystem",
    "PolitiFi",
    "Polkadot Ecosystem",
    "Polychain Capital Portfolio",
    "Polygon Ecosystem",
    "Polygon zkEVM Ecosystem",
    "Poolz Finance Launchpad",
    "Prediction Markets",
    "PreStocks Ecosystem",
    "Privacy Blockchain",
    "Privacy Coins",
    "Privacy-focused Browser",
    "Proof Ecosystem",
    "Proof of Memes Ecosystem",
    "Proof of Stake (PoS)",
    "Proof of Work (PoW)",
    "Provenance Ecosystem",
    "Pudgy Ecosystem",
    "PulseChain Ecosystem",
    "Puma Ecosystem",
    "Pump.fun Creator",
    "Pump.fun Ecosystem",
    "Pump Science Ecosystem",
    "Pundi AIFX Omnilayer Ecosystem",
    " Puzzle Games",
    "Qitmeer Network Ecosystem",
    "QL1 Ecosystem",
    "Q Mainnet Ecosystem",
    "Quai Network Ecosystem",
    "Quantum-Resistant",
    "Qubic Ecosystem",
    "Quest-to-Earn",
    "Racing Games",
    "Radix Ecosystem",
    "Rari Ecosystem",
    "Reactive Network Ecosystem",
    "Re.al Ecosystem",
    "RealT Tokens",
    "Real World Assets (RWA)",
    "Rebase Tokens",
    "Recruitment",
    "Redbelly Network Ecosystem",
    "Reddit Points",
    "Redstone Ecosystem",
    "Regenerative Finance (ReFi)",
    "Remona Tokenized Stocks [Deprecated]",
    "Remora Markets Tokenized rStocks",
    "Restaking",
    "Retail",
    "Robotics",
    "Rollup",
    "Rollups-as-a-Service (RaaS)",
    "Rollux Ecosystem",
    "Ronin Ecosystem",
    "Rootstock Ecosystem",
    "RPG",
    "RSS3 VSL Ecosystem",
    "Runes",
    "RWA Protocol",
    "Saakuru Ecosystem",
    "Saga Ecosystem",
    "Sanko Ecosystem",
    "Scroll Ecosystem",
    "Secret Ecosystem",
    "Sei Ecosystem (Deprecating)",
    "Seigniorage",
    "Sei Network Ecosystem",
    "Sequoia Capital Portfolio",
    "SGD Stablcoin",
    "Shibarium Ecosystem",
    "Shido Network Ecosystem",
    "ShimmerEVM Ecosystem",
    "Shooting Games",
    "SideChain",
    "Simulation Games",
    "Skale Ecosystem",
    "SmartBCH Ecosystem",
    "Smart Contract Platform",
    "SocialFi",
    "Software as a service",
    "Solana Ecosystem",
    "Solana Meme",
    "Solana Token-2022",
    "Somnia Ecosystem",
    "Soneium Ecosystem",
    "Songbird Ecosystem",
    "Sonic Ecosystem",
    "Sonic SVM Ecosystem",
    "Sora Ecosystem",
    "SPL22",
    "Spore.fun Ecosystem",
    "Sports",
    "Sports Games",
    "SRC-20",
    "Stablecoin Issuer",
    "Stablecoins",
    "Stable Ecosystem",
    "Stacks Ecosystem",
    "Starknet Ecosystem",
    "Stellar Ecosystem",
    "Step Network Ecosystem",
    "Sticker-Themed Coins",
    "Stock market-themed",
    "Storage",
    "Story Ecosystem",
    "Strategy Games",
    "STX.CITY Ecosystem",
    "Sui Ecosystem",
    "Sui Meme",
    "Sun Pump Ecosystem",
    "Superposition Ecosystem",
    "Superseed Ecosystem",
    "Supra Ecosystem",
    "Swellchain Ecosystem",
    "SX Rollup Ecosystem",
    "Synthetic",
    "Synthetic Asset",
    "Synthetic Dollar",
    "Synthetic Issuer",
    "Syscoin NEVM Ecosystem",
    "TAC Ecosystem",
    "Tap to Earn",
    "Taraxa Ecosystem",
    "Telegram Apps",
    "Telos Ecosystem",
    "tempCategory",
    "Tenet Ecosystem",
    "Terminal of Truths",
    "Terra Classic Ecosystem",
    "Terra Ecosystem",
    "Terraport Launchpad",
    "Tezos Ecosystem",
    "The Boy’s Club",
    "Theta Ecosystem",
    "ThunderCore Ecosystem",
    "TikTok Meme",
    "TimeFi",
    "Time.fun Ecosystem",
    "Titanchain Ecosystem",
    "TokenFi Launchpad",
    "Tokenized Assets",
    "Tokenized BTC",
    "Tokenized Commodities",
    "Tokenized Exchange-Traded Funds (ETFs)",
    "Tokenized Gold",
    "Tokenized Private Credit",
    "Tokenized Real Estate",
    "Tokenized Silver",
    "Tokenized Stock",
    "Tokenized Treasury Bills (T-Bills)",
    "Tokenized Treasury Bonds (T-Bonds)",
    "TokenSets Ecosystem",
    "Token Standards",
    "TON Ecosystem",
    "TON Meme",
    "Tourism",
    "Tower Defense Games",
    "Tradable Ecosystem",
    "Trading Bots",
    "Trading Card RWA Platform",
    "Tron Ecosystem",
    "TRON Meme",
    "Trump-Affiliated",
    "TRY Stablecoin",
    "Ultron Ecosystem",
    "Unichain Ecosystem",
    "Unit0 Network Ecosystem",
    "USD Stablecoin",
    "US Treasury-backed Stablecoin",
    "UTON Ecosystem",
    "ValueChain Ecosystem",
    "Vana Ecosystem",
    "Vanar Chain Ecosystem",
    "VeChain Ecosystem",
    "Velas Ecosystem",
    "Venom Ecosystem",
    "Venture Capital Portfolios",
    "Viction Ecosystem",
    "Virtual Reality",
    "Virtuals Protocol Ecosystem",
    "Voi Network Ecosystem",
    "VPN",
    "Vyvo Smart Chain Ecosystem",
    "Wallets",
    "Wall Street Bets Themed",
    "Wanchain Ecosystem",
    "Waves Ecosystem",
    "Wax Ecosystem",
    "Web 2 Brands",
    "WEMIX Ecosystem",
    "Winr Ecosystem",
    "Wojak-Themed",
    "World Chain Ecosystem",
    "World Liberty Financial Portfolio",
    "Wormhole Assets",
    "Wrapped-Tokens",
    "x402 Ecosystem",
    "XAI Ecosystem",
    "XDC Ecosystem",
    "X Layer Ecosystem",
    "Xone Ecosystem",
    "XRP Ledger Ecosystem",
    "XRPL EVM Ecosystem",
    "XT Smart Chain Ecosystem",
    "Yearn Ecosystem",
    "Yearn Vault Tokens",
    "Yield Aggregator",
    "Yield-Bearing",
    "Yield-Bearing Stablecoin",
    "Yield Farming",
    "Yield Optimizer",
    "Yield Tokenization Product",
    "Yield Tokenization Protocol",
    "YZi Labs (Prev. Binance Labs) Portfolio",
    "Zano Ecosystem",
    "Zedxion Ecosystem",
    "Zenon Ecosystem",
    "Zero Knowledge (ZK)",
    "Zero Network Ecosystem",
    "ZetaChain Ecosystem",
    "Ziliqa EVM Ecosystem",
    "Zilliqa Ecosystem",
    "Zircuit Ecosystem",
    "zkLink Nova Ecosystem",
    "ZkSync Ecosystem",
    "Zodiac-Themed",
    "Zoo-Themed",
    "Zora Creator",
    "Zora Ecosystem",
]
