name: PR Quality Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - '**'
jobs:
  get-affected:
    runs-on: ubuntu-latest
    outputs:
      affected_project: ${{ steps.set-project.outputs.affected_project }}
      affected_application: ${{ steps.set-application.outputs.affected_application }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm install

      - name: Get affected projects
        id: set-project
        run: |
          AFFECTED=$(npx nx show projects --affected --base=origin/main --head=HEAD | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "affected_project={\"project\": $AFFECTED}" >> $GITHUB_OUTPUT
      - name: Get affected applications
        id: set-application
        # TODO: update to test("_agent$") once data_agent has integration tests
        run: |
          AFFECTED=$(npx nx show projects --affected --base=origin/main --head=HEAD |
            jq -R -s -c 'split("\n") | map(select(. != "" and test("invest_agent$")))')

          echo "affected_application={\"project\": $AFFECTED}" >> $GITHUB_OUTPUT

  lint-check:
    needs: get-affected
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-affected.outputs.affected_project) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - run: |
          npm install
          npx nx install ${{ matrix.project }}

      - name: Run lint check
        run: npx nx lint ${{ matrix.project }}

  test:
    needs: get-affected
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-affected.outputs.affected_project) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - run: |
          npm install
          npx nx install ${{ matrix.project }}

      # TODO: See how to handle this better. Maybe mocking every external API with MockServer.
      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > ${{ matrix.project }}/.env

      - name: Run unit tests
        run: npx nx test ${{ matrix.project }}

  test-integration:
    needs: get-affected
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.get-affected.outputs.affected_application) }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          npm install
          npx nx install ${{ matrix.project }}

      # TODO: See how to handle this better. Maybe mocking every external API with MockServer.
      - name: Create .env file from GitHub Secret
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > ${{ matrix.project }}/.env

      - name: Run integration tests
        run: npx nx test:integration ${{ matrix.project }}
